[build]
target = "index.html"
dist = "dist"
release = false

[watch]
watch = [
    # also watch style folder
    "./style/css/"
]

[[hooks]]
stage = "build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "cd ./style && npm run build"
]
